### ISSUE TITLE
Received invalid server message, invalid control line

### ISSUE THREAD

**Issue by Kvikal** [davidMcneil/rants#1]
Hello,

I have run into an issue connecting to the official NATS server (gnatsd).

Each connection attempt fails with following message:

`Received invalid server message, err: invalid control line "INFO {\"server_id\":\"EIcTs1hcrlywWCrsUATcqP\",\"version\":\"1.1.0\",\"git_commit\":\"add6d79\",\"go\":\"go1.9.4\",\"host\":\"0.0.0.0\",\"port\":4222,\"auth_required\":false,\"tls_required\":false,\"tls_verify\":false,\"max_payload\":1048576} \r\n"`

The server version is quite old now, so it might be a gnatsd bug.

**Comment by Kvikal** [comment]
This issue does not seem to occur with gnatsd 1.4.0.

**Comment by davidMcneil** [comment]
Thank you very much for opening an issue!

I believe the specific reason this `INFO` message did not parse is that it is missing the [`proto`](https://nats-io.github.io/docs/nats_protocol/nats-protocol.html#info) field. This field was added in version 1.2 of the server. I am working on improving the parser to make the error message more informative and will also make the `proto` field optional to support older servers.

**Comment by davidMcneil** [comment]
Resolved in version 0.3.0 by commit [4e9929](https://github.com/davidMcneil/rants/commit/4e9929e974366f82200eb86cc79f9dbc4680f6f8).
