### ISSUE TITLE
task::block_on(client.connect()) crash

### ISSUE THREAD

**Issue by DAOCUONG** [davidMcneil/rants#13]
pub async fn connect(&self) 
I tried to use task::block_on (async-std) for above connect function  it crashed

**Comment by davidMcneil** [comment]
Unfortunately, `rants` only supports the [`tokio`](https://crates.io/crates/tokio) runtime. This is because there is currently no runtime agnostic way to spawn a future. This relates to the discussion [here](https://users.rust-lang.org/t/poll-async-await-lets-talk-about-executors/31753).

**Comment by DAOCUONG** [comment]
Thanks you for your info, i need to use actor model for handle nat connection there for i cant call client.connect from async function. I want to block_on client.connet(). as you mention tokio runtime can do that i have tried following code: 

>
    let f = natsclient.connect();

    let mut rt = Runtime::new().unwrap();
    rt.block_on(f);

> 

I got error lock_on(f);
   |                 ^ the trait `futures::future::Future` is not implemented for `impl core::future::future::Future`

**Comment by DAOCUONG** [comment]
FYI Using futures::executor also crashed    

> 

    let f = natsclient.connect();
    futures::executor::block_on(f);

>

**Comment by davidMcneil** [comment]
I added an [example](https://github.com/davidMcneil/rants/blob/master/tests/blocking.rs) of using the client in a blocking context. Although, if you are using the client synchronously it might be better to use one of the [other clients](https://github.com/davidMcneil/rants#alternatives).

**Comment by DAOCUONG** [comment]
@davidMcneil  thanks you so much for helping i absolutely want to do async way, i using nats client with actor model (riker)  super visor will send message for all worker to connect , i would like use client.connect async way too

**Comment by davidMcneil** [comment]
@DAOCUONG Cool, sounds like an interesting use case. I found [this issue](https://github.com/riker-rs/riker/issues/45) in riker that might answer some questions in regard to spawning a future within an actor. 

I am going to close this for now, but feel free to reopen or open another issue if you run into more problems. Thanks for using the library!
