### ISSUE TITLE
Allow getting subject name

### ISSUE THREAD

**Issue by nevi-me** [davidMcneil/rants#14]
I noticed that I can't retrieve the name of a `Subject`. If I subscribe to a wildcard/prefix subject such as `notifications.>`, I want to be able to inspect which subject I received (e.g. `notifications.emergency.accident`, and react to it accordingly.

It looks like the only thing I can do is use `Display`.

**Comment by davidMcneil** [comment]
Thank you for taking the time to open an issue. 

I am not sure I fully follow what you are trying to accomplish. Would you mind posting code showing what methods would be useful to have added to the library?

If you want the string representation of a `Subject` you can use [`to_string`](https://doc.rust-lang.org/std/string/trait.ToString.html#tymethod.to_string). If you want to get the `Subject` of a recieved message you can use the [`subject`](https://docs.rs/rants/0.4.2/rants/struct.Msg.html#method.subject) method.

I could see it being useful to have a `matches` (or something like that) method on `Subject` that checks if one `Subject` is matched by another `Subject`'s wildcard's. Is that what you are getting at?

**Comment by nevi-me** [comment]
My apologies, I hadn't seen that ToString is implemented on Subject. I'm sorted now, happy new year!

**Comment by baadc0de** [comment]
I'd like to comment that it would be great to have access to the `tokens` that make up the subject. For example when subscribing to `a.*.status` rants already has the middle wildcard value populated in the `tokens` field. Getting that instead of going `to_string` seems weird to me.
