### ISSUE TITLE
How to set the timeout of a request

### ISSUE THREAD

**Issue by ufoscout** [davidMcneil/rants#23]
How can I set the timeout of a request?
This simple test hangs forever at the `client.request(...)` line because nobody replies to the request; anyway, I would like it to fail after some time:

```rust
#[tokio::test]
async fn response_should_timeout() {
    let subject = "test_subject".parse().unwrap();

    let client = rants::Client::new(vec!["127.0.0.1:4222".parse().unwrap()]);
    client.connect().await;

    client.publish(&subject, b"").await.unwrap();
    println!("Publish -> ok");

    client.request(&subject, b"").await.unwrap();
    println!("Request -> ok");  // <-- this is never printed
}
```

**Comment by davidMcneil** [comment]
You can use [`tokio::time::timeout`](https://docs.rs/tokio/0.2.13/tokio/time/fn.timeout.html).

```rust
#[tokio::test]
async fn response_should_timeout() {
    use std::time::Duration;

    let subject = "test_subject".parse().unwrap();

    let client = rants::Client::new(vec!["127.0.0.1:4222".parse().unwrap()]);
    client.connect().await;

    client.publish(&subject, b"").await.unwrap();
    println!("Publish -> ok");

    assert!(tokio::time::timeout(Duration::from_secs(5), client.request(&subject, b"")).await.is_err());
    println!("Request -> ok");  // <-- this is never printed
}

```

**Comment by ufoscout** [comment]
Hi @davidMcneil 
thanks for your suggestion.
How does it work exactly? after the tokio timeout is the request closed? I mean, the request creates a subscription to a temporary subject, is this subscription deleted after the timeout or maybe there's some kind of leak?
Finally, I would propose to add a global timeout to the client itself, this is a feature that a user expects to find in whatever library that performs remote calls.

**Comment by baadc0de** [comment]
I have not tested it, but I think if the future is dropped (cancelled) due to `tokio::time::timeout`, the client code in `request` looks like it has some cleanup code at the end.

**Comment by davidMcneil** [comment]
> is this subscription deleted after the timeout or maybe there's some kind of leak?

Yeah, unfortunately the subscription is leaked. See issue #4. This is actually currently being worked on in #25.

**Comment by davidMcneil** [comment]
This is now possible with [request_with_timeout](https://docs.rs/rants/0.4.4/rants/struct.Client.html#method.request_with_timeout)
